### ISSUE TITLE
Use CakePHP's own functions

### ISSUE THREAD

**Issue by sevvlor** [Finley7/Chatzor5#1]
I have seen that you've created your own url parser. in `UbbComponent.php`. I want to point out that CakePHP has an Autolink function http://book.cakephp.org/3.0/en/views/helpers/text.html#linking-urls

**Comment by Finley7** [comment]
I did not know that, I will implement this in one of the next updates.

**Comment by RosiersRobin** [comment]
Than this can be marked as enchantment?
